bundler_args: "--standalone --binstubs --without development"
script: script/test_all
services: mongodb
before_script:
  - mysql -e 'create database will_paginate;'
  - psql -c 'create database will_paginate;' -U postgres
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
  - Gemfile.rails3.0
  - Gemfile.rails3.1
  - Gemfile.rails3.2
  - Gemfile.rails-edge
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile.rails-edge
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.2
      gemfile: Gemfile.rails-edge
    - rvm: 1.9.2
      gemfile: Gemfile
